apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: identity-service
  namespace: vera
spec:
  ingressClassName: traefik
  rules:
    - host: identity.vera.sninjo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: identity-service
                port:
                  number: 80
